### PR TITLE
[NAMING] Use a standard group name

### PR DESCRIPTION
**Pull request by CedrickFlocon**
Screenshot 2020-11-09 at 10 55 17

### CODE REVIEW

**Comment by cosic** [comment]
@CedrickFlocon Hi! I'm not sure that it's a good idea. For example, I looked at the [Triple-T/gradle-play-publisher](https://github.com/Triple-T/gradle-play-publisher) for publishing into Google Play. They are using separated Plugin group name:
```Publishing tasks
----------------
bootstrap - Downloads the Play Store listing metadata for all variants.
   See https://github.com/Triple-T/gradle-play-publisher#quickstart
bootstrapRelease - Downloads the Play Store listing metadata for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#quickstart
installDebugPrivateArtifact - Launches an intent to install an Internal Sharing artifact for variant 'debug'.
   See https://github.com/Triple-T/gradle-play-publisher#installing-internal-sharing-artifacts
installReleasePrivateArtifact - Launches an intent to install an Internal Sharing artifact for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#installing-internal-sharing-artifacts
installStagePrivateArtifact - Launches an intent to install an Internal Sharing artifact for variant 'stage'.
   See https://github.com/Triple-T/gradle-play-publisher#installing-internal-sharing-artifacts
promoteArtifact - Promotes a release for every variant.
   See https://github.com/Triple-T/gradle-play-publisher#promoting-artifacts
promoteReleaseArtifact - Promotes a release for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#promoting-artifacts
publish - Uploads APK or App Bundle and all Play Store metadata for every variant.
   See https://github.com/Triple-T/gradle-play-publisher#managing-artifacts
publishApk - Uploads APK for every variant.
   See https://github.com/Triple-T/gradle-play-publisher#publishing-apks
publishBundle - Uploads App Bundle for every variant.
   See https://github.com/Triple-T/gradle-play-publisher#publishing-an-app-bundle
publishListing - Uploads all Play Store metadata for every variant.
   See https://github.com/Triple-T/gradle-play-publisher#publishing-listings
publishProducts - Uploads all Play Store in-app products for every variant.
   See https://github.com/Triple-T/gradle-play-publisher#publishing-in-app-products
publishRelease - Uploads APK or App Bundle and all Play Store metadata for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#managing-artifacts
publishReleaseApk - Uploads APK for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#publishing-apks
publishReleaseBundle - Uploads App Bundle for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#publishing-an-app-bundle
publishReleaseListing - Uploads all Play Store metadata for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#publishing-listings
publishReleaseProducts - Uploads all Play Store in-app products for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#publishing-in-app-products
uploadDebugPrivateApk - Uploads Internal Sharing APK for variant 'debug'.
   See https://github.com/Triple-T/gradle-play-publisher#uploading-an-internal-sharing-artifact
uploadDebugPrivateBundle - Uploads Internal Sharing App Bundle for variant 'debug'.
   See https://github.com/Triple-T/gradle-play-publisher#uploading-an-internal-sharing-artifact
uploadReleasePrivateApk - Uploads Internal Sharing APK for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#uploading-an-internal-sharing-artifact
uploadReleasePrivateBundle - Uploads Internal Sharing App Bundle for variant 'release'.
   See https://github.com/Triple-T/gradle-play-publisher#uploading-an-internal-sharing-artifact
uploadStagePrivateApk - Uploads Internal Sharing APK for variant 'stage'.
   See https://github.com/Triple-T/gradle-play-publisher#uploading-an-internal-sharing-artifact
uploadStagePrivateBundle - Uploads Internal Sharing App Bundle for variant 'stage'.
   See https://github.com/Triple-T/gradle-play-publisher#uploading-an-internal-sharing-artifact
```
And when I'm using the plugin it is convenient for me to look for the tasks of my plugin in a separate group to see that it works.

**Comment by CedrickFlocon** [comment]
Yes I saw that you were very inspired by this plugin,
Fortunately not every plugin creates a group. it would have been a mess.
Gradle Play publisher : 
https://github.com/Triple-T/gradle-play-publisher/blob/master/common/utils/src/main/kotlin/com/github/triplet/gradle/common/utils/Constants.kt#L6
Gradle Publishing plugin :
https://docs.gradle.org/current/javadoc/org/gradle/api/publish/plugins/PublishingPlugin.html#PUBLISH_TASK_GROUP
````
public static final String PUBLISH_TASK_GROUP = "publishing";
````

**Comment by cosic** [comment]
Ok )) you convinced me. Could you change the group name from `publishing` to `Publishing` and resolve conflicts?

**Comment by CedrickFlocon** [comment]
@cosic I think it's better to rely on `PublishingPlugin.PUBLISH_TASK_GROUP` see update

**Pull request merged**
